sylius_resource:
    resources:
        app.sponsor:
            classes:
                model: App\Entity\Sponsoring\Sponsor
                form: App\Form\Type\Resource\Sponsoring\SponsorType
            templates: '@SyliusAdmin/Crud'
        
        app.sponsor_logo:
            classes:
                model: App\Entity\Sponsoring\SponsorLogo
                form: App\Form\Type\Resource\Sponsoring\SponsorLogoType

sylius_grid:
    grids:
        app_admin_sponsor:
            driver:
                name: doctrine/orm
                options:
                    class: '%app.model.sponsor.class%'
            filters:
                code:
                    type: string
                    label: app.ui.code
                name:
                    type: string
                    label: app.ui.name
                tier:
                    type: select
                    label: app.ui.tier
                    form_options:
                        choices:
                            app.ui.sponsor_tier_host: Host
                            app.ui.sponsor_tier_regular: Regular
            fields:
                code:
                    type: string
                    label: app.ui.code
                    sortable: ~
                name:
                    type: string
                    label: app.ui.name
                    sortable: ~
                tier:
                    type: twig
                    label: app.ui.tier
                    sortable: ~
                    options:
                        template: "@SyliusAdmin/Grid/Field/_sponsor_tier.html.twig"
                logo:
                    type: twig
                    label: app.ui.logo
                    options:
                        template: "@SyliusAdmin/Grid/Field/_sponsor_logo.html.twig"
            actions:
                main:
                    create:
                        type: create
                        label: sylius.ui.create
                item:
                    delete:
                        type: delete
                        label: sylius.ui.delete
                    update:
                        type: update
                        label: sylius.ui.update

sylius_ui:
    events:
        app.admin.sponsor.create.javascripts:
            blocks:
                preview_image:
                    template: '@SyliusAdmin/Sponsoring/Sponsor/_preview_image.html.twig'
                    priority: 10
        app.admin.sponsor.update.javascripts:
            blocks:
                preview_image:
                    template: '@SyliusAdmin/Sponsoring/Sponsor/_preview_image.html.twig'
                    priority: 10

liip_imagine:
    filter_sets:
        app_admin_sponsor_logo_thumbnail:
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
        app_shop_sponsor_logo_banner:
            filters:
                thumbnail: { size: [120, 120], mode: outbound }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Form\Type\Resource\Sponsoring\SponsorType:
        arguments:
            - '%app.model.sponsor.class%'
            - ['sylius']

    App\Form\Type\Resource\Sponsoring\SponsorLogoType:
        arguments:
            - '%app.model.sponsor_logo.class%'
            - ['sylius']
    
    app.listener.sponsor_logo_upload_listener:
        class: Sylius\Bundle\CoreBundle\EventListener\ImageUploadListener
        tags:
            - { name: kernel.event_listener, event: app.sponsor.pre_create, method: uploadImage }
            - { name: kernel.event_listener, event: app.sponsor.pre_update, method: uploadImage }
